// SCAFFOLD ONLY. Real implementation pulls capture_table.h (generated by
// scripts/sync_capture_table.ps1) and queries ApState::captures_unlocked.

#include "CaptureGate.hpp"

#include "../ap/ApState.hpp"
#include "../util/Log.hpp"

namespace smoap::game {

std::uint8_t captureBitFor(const std::string& cap_name) {
    // M5: replace with generated table lookup.
    (void)cap_name;
    return 0xff;
}

bool captureBlocked(const std::string& cap_name) {
    const std::uint8_t bit = captureBitFor(cap_name);
    if (bit == 0xff) return false;  // unknown -> don't block (fail open)
    return !smoap::ap::ApState::instance().captures_unlocked.test(bit);
}

std::string nameForHackData(/* const PlayerHackData* data */) {
    return {};  // M5
}

void playSE_NG() {
    // al::startSe(/* SE_NG */, /* ... */);
    SMOAP_LOG_INFO("playSE_NG (stub)");
}

}  // namespace smoap::game
