// Capture lock query + cap-name <-> bit-index mapping.
//
// The bit-index table (capture_table.h) is generated by
// scripts/sync_capture_table.ps1 from apworld/data/items.json so the Switch
// and bridge cannot drift on cap-name <-> id assignment.

#pragma once

#include <cstdint>
#include <string>

namespace smoap::game {

// Returns the bit index for `cap_name` (matching apworld's enemy ordering)
// or 0xff if the name is unknown.
std::uint8_t captureBitFor(const std::string& cap_name);

// True if the player has *not* received the unlock item for this capture.
bool captureBlocked(const std::string& cap_name);

// Resolve the capture's canonical name from a PlayerHackData / hack-target.
// (Implementation pulls from sead string tables in the game.)
std::string nameForHackData(/* const PlayerHackData* data */);

// Plays the standard "no" SE used by the game when something is denied.
void playSE_NG();

}  // namespace smoap::game
