# Generate switch-mod/src/ap/capture_table.h from apworld/data/items.json.
#
# Run after pulling new apworld data so the Switch's bit-index assignments
# stay in sync with the bridge's classification.

$ErrorActionPreference = "Stop"

$repoRoot   = (Resolve-Path "$PSScriptRoot\..").Path
$itemsPath  = Join-Path $repoRoot "apworld\smo_archipelago\data\items.json"
$outPath    = Join-Path $repoRoot "switch-mod\src\ap\capture_table.h"

if (-not (Test-Path $itemsPath)) {
  throw "items.json not found at $itemsPath"
}

$items    = Get-Content $itemsPath -Raw | ConvertFrom-Json
$captures = @($items | Where-Object { $_.category -contains "Capture" } | ForEach-Object { $_.name })

if ($captures.Count -eq 0) {
  throw "no Capture-category items found in $itemsPath"
}

$header = @"
// AUTO-GENERATED by scripts/sync_capture_table.ps1 — DO NOT EDIT.
// Source: apworld/smo_archipelago/data/items.json (Capture category)
// Count: $($captures.Count)

#pragma once

#include <array>
#include <string_view>

namespace smoap::game {

inline constexpr std::array<std::string_view, $($captures.Count)> kCaptureNames = {
"@

$lines = $captures | ForEach-Object { "    `"$_`"," }
$body  = ($lines -join "`n")

$footer = @"

};

}  // namespace smoap::game
"@

$content = $header + $body + $footer
$dir = Split-Path $outPath -Parent
if (-not (Test-Path $dir)) { New-Item -ItemType Directory -Path $dir -Force | Out-Null }
Set-Content -Path $outPath -Value $content -Encoding UTF8

Write-Host "Wrote $($captures.Count) capture names to $outPath"
