"""Generate switch-mod/src/ap/capture_table.h from apworld/data/items.json.

Run after pulling new apworld data so the Switch's bit-index assignments
stay in sync with the bridge's classification.

When apworld/smo_archipelago/client/data/capture_map.json is also present
(extracted by scripts/extract_shine_map.py from the user's local NSP dump),
emits a second parallel `kCaptureHackNames` array so the Switch-side gate
can look up by SMO-internal hack_name (e.g. "TRex", "Wanwan") rather than
the apworld English name (e.g. "T-Rex", "Chain Chomp"). PlayerHackKeeper::
getCurrentHackName returns the hack_name, so without this mapping the
M7 deny path fail-opens for every diverged cap. Identity passthrough for
the ~36 captures whose apworld name matches the hack_name 1:1.

This is a Python port of sync_capture_table.ps1 — use whichever your shell
prefers. Both produce identical output.

Usage:
    python scripts/sync_capture_table.py
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path


def main(argv: list[str] | None = None) -> int:
    # Defaults are computed off this script's location, matching the dev
    # source-checkout layout. When invoked from the wizard inside AP's
    # frozen Launcher the bundled apworld layout doesn't match those
    # defaults (items.json is at <bundled>/data/ rather than
    # <bundled>/apworld/smo_archipelago/data/, switch_mod has an
    # underscore not a hyphen, capture_map.json lives in %APPDATA%/...
    # /data/ where the extractor wrote it). The wizard passes explicit
    # --items / --capture-map / --out so all three paths resolve.
    here = Path(__file__).resolve().parent.parent
    default_items = here / "apworld" / "smo_archipelago" / "data" / "items.json"
    default_out = here / "switch-mod" / "src" / "ap" / "capture_table.h"
    default_capture_map = (
        here / "apworld" / "smo_archipelago" / "client" / "data" / "capture_map.json"
    )

    ap = argparse.ArgumentParser(description=__doc__.split("\n\n", 1)[0])
    ap.add_argument("--items", type=Path, default=default_items,
                    help=f"apworld items.json (default: {default_items})")
    ap.add_argument("--out", type=Path, default=default_out,
                    help=f"output capture_table.h (default: {default_out})")
    ap.add_argument("--capture-map", type=Path, default=default_capture_map,
                    help=f"optional capture_map.json for hack_name mapping "
                         f"(default: {default_capture_map})")
    args = ap.parse_args(argv)

    items_path = args.items
    out_path = args.out
    capture_map_path = args.capture_map

    if not items_path.exists():
        print(f"items.json not found at {items_path}", file=sys.stderr)
        return 1

    items = json.loads(items_path.read_text(encoding="utf-8"))
    captures = [it["name"] for it in items if "Capture" in (it.get("category") or [])]

    if not captures:
        print(f"no Capture-category items found in {items_path}", file=sys.stderr)
        return 1

    # Build cap -> hack_name lookup. Missing capture_map.json → all identity.
    cap_to_hack: dict[str, str] = {}
    if capture_map_path.exists():
        entries = json.loads(capture_map_path.read_text(encoding="utf-8"))
        cap_to_hack = {e["cap"]: e["hack_name"] for e in entries if "cap" in e and "hack_name" in e}
    hack_names = [cap_to_hack.get(name, name) for name in captures]
    diverged = sum(1 for cap, hack in zip(captures, hack_names) if cap != hack)

    cap_body  = "\n".join(f'    "{name}",' for name in captures)
    hack_body = "\n".join(f'    "{name}",' for name in hack_names)
    source_line = (
        "// Hack-name mapping source: apworld/smo_archipelago/client/data/capture_map.json"
        if capture_map_path.exists()
        else "// Hack-name mapping: identity (capture_map.json absent — run "
             "scripts/extract_shine_map.py to populate)"
    )
    content = (
        "// AUTO-GENERATED by scripts/sync_capture_table.{ps1,py} — DO NOT EDIT.\n"
        "// Source: apworld/smo_archipelago/data/items.json (Capture category)\n"
        f"{source_line}\n"
        f"// Count: {len(captures)} (diverged hack/cap pairs: {diverged})\n"
        "\n"
        "#pragma once\n"
        "\n"
        "#include <array>\n"
        "#include <string_view>\n"
        "\n"
        "namespace smoap::game {\n"
        "\n"
        f"inline constexpr std::array<std::string_view, {len(captures)}> kCaptureNames = {{\n"
        f"{cap_body}\n"
        "};\n"
        "\n"
        "// Parallel to kCaptureNames — kCaptureHackNames[i] is the SMO-internal\n"
        "// hack_name (what PlayerHackKeeper::getCurrentHackName returns) for the\n"
        "// apworld capture at kCaptureNames[i]. captureBitFor() searches both so\n"
        "// the M7 deny path matches by hack_name and the M6-B apply path matches\n"
        "// by apworld cap. Identity entries (same value as kCaptureNames) are\n"
        "// harmless duplicates.\n"
        f"inline constexpr std::array<std::string_view, {len(captures)}> kCaptureHackNames = {{\n"
        f"{hack_body}\n"
        "};\n"
        "\n"
        "}  // namespace smoap::game\n"
    )

    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(content, encoding="utf-8")
    print(f"Wrote {len(captures)} capture names to {out_path} "
          f"({diverged} diverged hack/cap pairs, "
          f"capture_map.json {'found' if capture_map_path.exists() else 'MISSING — using identity'})")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
