"""Generate switch-mod/src/ap/capture_table.h from apworld/data/items.json.

Run after pulling new apworld data so the Switch's bit-index assignments
stay in sync with the bridge's classification.

This is a Python port of sync_capture_table.ps1 — use whichever your shell
prefers. Both produce identical output.

Usage:
    python scripts/sync_capture_table.py
"""

from __future__ import annotations

import json
import sys
from pathlib import Path


def main() -> int:
    here = Path(__file__).resolve().parent.parent
    items_path = here / "apworld" / "smo_archipelago" / "data" / "items.json"
    out_path = here / "switch-mod" / "src" / "ap" / "capture_table.h"

    if not items_path.exists():
        print(f"items.json not found at {items_path}", file=sys.stderr)
        return 1

    items = json.loads(items_path.read_text(encoding="utf-8"))
    captures = [it["name"] for it in items if "Capture" in (it.get("category") or [])]

    if not captures:
        print(f"no Capture-category items found in {items_path}", file=sys.stderr)
        return 1

    body_lines = "\n".join(f'    "{name}",' for name in captures)
    content = (
        "// AUTO-GENERATED by scripts/sync_capture_table.{ps1,py} — DO NOT EDIT.\n"
        "// Source: apworld/smo_archipelago/data/items.json (Capture category)\n"
        f"// Count: {len(captures)}\n"
        "\n"
        "#pragma once\n"
        "\n"
        "#include <array>\n"
        "#include <string_view>\n"
        "\n"
        "namespace smoap::game {\n"
        "\n"
        f"inline constexpr std::array<std::string_view, {len(captures)}> kCaptureNames = {{\n"
        f"{body_lines}\n"
        "};\n"
        "\n"
        "}  // namespace smoap::game\n"
    )

    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(content, encoding="utf-8")
    print(f"Wrote {len(captures)} capture names to {out_path}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
